import { ExceptionsManager } from '../helpers';
import tx_2628876349522661236 from './tx_2628876349522661236';
import block_11230047540985942454 from './block_11230047540985942454';
import block_8798611478810602119 from './block_8798611478810602119';
import block_9319557141665650935 from './block_9319557141665650935';
import block_4415883780827388428 from './block_4415883780827388428';
import block_3299949874300391144 from './block_3299949874300391144';
import block_11758944382789034562 from './block_11758944382789034562';
import block_9107296206050614818 from './block_9107296206050614818';
import block_3418472308088137242 from './block_3418472308088137242';

const allExceptionCreator: Array<(exc: ExceptionsManager) => Promise<void>> = [
  tx_2628876349522661236,
  block_11230047540985942454,
  block_8798611478810602119,
  block_9319557141665650935,
  block_4415883780827388428,
  block_3299949874300391144,
  block_11758944382789034562,
  block_9107296206050614818,
  block_3418472308088137242
];

export { allExceptionCreator };
